export enum Financement {
  CONTRAT_DOCTORAL = 'CONTRAT_DOCTORAL',
  CIFRE = 'CIFRE',
  PROJET_ANR = 'PROJET_ANR',
  PROJET_EUROPEEN = 'PROJET_EUROPEEN',
  AUTO_FINANCEMENT = 'AUTO_FINANCEMENT',
  BOURSE_ETRANGERE = 'BOURSE_ETRANGERE',
  AUTRE = 'AUTRE'
}
