package com.lipn.app.enums;

public enum StatutPropositionEnum {
    BROUILLON,
    SOUMISE,
    EN_ATTENTE_VALIDATION_EQUIPE,
    REFUSE_EQUIPE,
    VALIDEE_EQUIPE,
    EN_ATTENTE_VALIDATION_DIRECTION,
    REFUSE_DIRECTION,
    VALIDEE_DIRECTION,
    EN_COMITE,
    EN_ATTENTE_AUDITION,
    AUDITION_REALISEE,
    CLASSEE,
    ACCEPTEE,
    REFUSEE
}
